### ISSUE TITLE
Folder Remnants with Untouchable File Permissions

### ISSUE THREAD

**Issue by chase-skibeness** [microsoft/SurfaceDeploymentAccelerator#28]
Running the script created a directory, C:\Users\<My User>\AppData\Local\Temp\Mount , however the script wasn't able to complete in creating the deployment image. Re-running the script resulted in an error message that while Mount isn't empty the script can't be run.  Attempting to delete the folder and it's contents has resulted in permissions issues both as administrator and local user.

FIX:
Opening the Folder Properties > Security Tab > Advanced 
change ownership and all children's ownership to the Administrator group 
Replace all child object permission entries with inheritable permission entries from this object
Delete as normal

Feel free to assign to me and I can expand the folder detection to include a delete option for the user

**Comment by cluberti** [comment]
Unfortunately, this is a bug I've yet to be able to fully handle and is a dism/windows image handling issue, rather than a tool issue - the script attempts to remove permissions and reset when a run is attempted after a failure, to avoid this situation.  Your steps are the unfortunate result of this issue.

I've not found a good way to automate it (I've tried), but if you feel that you want to take a stab at it, submit a fix and I'll commit it if it doesn't break anything further :).
